### ISSUE TITLE
playstyle intros does not seem to load for villain greeters.

### ISSUE THREAD

**Issue by Bgagger** [basstabs/NEForumMessenger#11]
yeah. just gives a blank screen.

**Comment by Bgagger** [comment]
trying again though, loads on second try. not sure if it's inconsistent or just takes a while to load.

**Comment by basstabs** [comment]
Unable to reproduce this error. Successfully viewed each greeter nabber's profile with no significant time delay. May have been a network issue.

Whose intro were you trying to access?

**Comment by basstabs** [comment]
Found potential cause: Certain play style intros result in a 404 response. Investigating

**Comment by basstabs** [comment]
Fixed an issue with the same symptoms. Unsure if it is the same bug or not, will wait until the OP has time to verify that the issue no longer exists.
