### ISSUE TITLE
Messages do not open

### ISSUE THREAD

**Issue by Bgagger** [basstabs/NEForumMessenger#21]
Bug found when testing on Android 4.4 (API 19):
Messages in the inbox won't open. When tapping/clicking a subject found in the list, it flashes to confirm the button is pressed, but then nothing else happens.

Tested for several different inboxes for different users in the main list. The problem seems consistent, have so far not been able to open any messages.

The same has been tested and found working just fine for the same inboxes on Android 6.0 (API 23)

**Comment by basstabs** [comment]
Possibly fixed. Fixed on an emulator, unknown if that also fixes the issue on physical devices.

https://github.com/basstabs/NEForumMessenger/releases/tag/0.0.6.1

Here is the possibly fixed version.

**Comment by Bgagger** [comment]
V 0.0.6.1 now tested and confirmed working on live device running Android 4.4
