### ISSUE TITLE
non ascii character encoding.

### ISSUE THREAD

**Issue by Bgagger** [basstabs/NEForumMessenger#22]
Non ascii characters in messages does not display correctly.
For example å ä or ö.
The forum boardware uses the UTF-8 charset. It would be good if UTF-8 support could be added to the app as well, for consistency.

**Comment by basstabs** [comment]
Should be fixed in the next update. Some seemingly undesirable functionality with Volley was causing the XML response to not use UTF-8 encoding, but switching over to the CSV export seems to have resolved the issue for now
