### ISSUE TITLE
RP Message frequency

### ISSUE THREAD

**Issue by Bgagger** [basstabs/NEForumMessenger#23]
A new value has been added to forum profiles.
RP Message frequency
Which works in very much the same manner as the RP pref profile field. It works as an optional value on the forum, so is not always set, but will change if the game settings are altered.
If it could be added to the profile that would be handy. Though not critical.

<dt>RP Message frequency:</dt> <dd>Usually daily</dd>

**Comment by basstabs** [comment]
Less than a one line change. Should show up in the next update.
