### ISSUE TITLE
Notify the user if no threads are found

### ISSUE THREAD

**Issue by basstabs** [basstabs/NEForumMessenger#5]
If no threads are found in the inbox, notify the user and halt the infinite refresh.

In Progress

**Comment by Bgagger** [comment]
Bug confirmed. Tried searching for a user that was not online, the latest newcomer Ashlee Morgan. The player was found and color coded correctly for account type. But when I clicked the name, the "loading" circle appeared and started spinning. For over 30 minutes, with nothing more happening, before I aborted by the back button. (a timeout limit seems in order here, or a way to recognize that no message can be found).
This player never sent me any PMs.

Tested a user that was online and got the last PM they sent me displayed. backing from there got me a list of past PMs.

**Comment by basstabs** [comment]
Should function now. Counts the number of threads found, halting the loading symbol whenever the network responds
